version = "1.0"

[metadata]

[environment]
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
POCHI_LOG = "debug"
POCHI_API_KEY = "${POCHI_API_KEY}"
PARAGON_PROJECT_ID = "${PARAGON_PROJECT_ID}"
PARAGON_USER_TOKEN = "${PARAGON_USER_TOKEN}"
MAILGUN_LIST_ADDRESS = "${MAILGUN_LIST_ADDRESS}"
MAILGUN_MEMBER_ADDRESS = "${MAILGUN_MEMBER_ADDRESS}"

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]
POCHI_LOG = "debug"
PARAGON_PROJECT_ID = "${PARAGON_PROJECT_ID}"
PARAGON_USER_TOKEN = "${PARAGON_USER_TOKEN}"
MAILGUN_LIST_ADDRESS = "${MAILGUN_LIST_ADDRESS}"
MAILGUN_MEMBER_ADDRESS = "${MAILGUN_MEMBER_ADDRESS}"

[solution.env]
