version = "1.0"

[metadata]

[environment]
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
POCHI_LOG = "debug"
POCHI_API_KEY = "${POCHI_API_KEY}"
NEXT_PUBLIC_PARAGON_PROJECT_ID = "${NEXT_PUBLIC_PARAGON_PROJECT_ID}"
PARAGON_SIGNING_KEY = "${PARAGON_SIGNING_KEY}"

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]
POCHI_LOG = "debug"
NEXT_PUBLIC_PARAGON_PROJECT_ID = "${NEXT_PUBLIC_PARAGON_PROJECT_ID}"
PARAGON_SIGNING_KEY = "${PARAGON_SIGNING_KEY}"

[solution.env]
